### ISSUE TITLE
Remove the `required` field from CSV

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-auditlogging-operator#21]
Common services operators don’t need to specify `spec.customresourcedefinitions.required`  in their CSV.  

In the Q1 release, there is no dependency management from ODLM, all the required operators need to be added into `OperandRequest` instance.

In the Q2 release, operators will use `OperandRequest` to manage their own dependencies.

https://github.com/IBM/ibm-auditlogging-operator/blob/master/deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml#L53

**Comment by znhafeez** [comment]
addressed issue in PR: https://github.com/IBM/ibm-auditlogging-operator/pull/23
