### ISSUE TITLE
sync up package name in ODLM operator

### ISSUE THREAD

**Issue by horis233** [IBM/ibm-auditlogging-operator#8]
In  `Ibm-auditlogging-operator` package name is `ibm-auditlogging-operator`

https://github.com/IBM/ibm-auditlogging-operator/blob/master/deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml#L5

In ODLM the package name is `ibm-auditlogging-operator-app`

https://github.com/IBM/operand-deployment-lifecycle-manager/blob/master/deploy/crds/operator.ibm.com_v1alpha1_operandregistry_cr.yaml#L73

Need to update https://github.com/IBM/ibm-auditlogging-operator/blob/master/deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml#L5

**Comment by znhafeez** [comment]
PR for fix: https://github.com/IBM/ibm-auditlogging-operator/pull/9

**Comment by hbradfield** [comment]
Fixed. Deploys from OLDM and starts
